### ISSUE TITLE
How does this code handle gaps?

### ISSUE THREAD

**Issue by slidenerd** [frnxstd/live-binance#1]
you were disconnected for 2 mins and then reconnected again, now you have 2 missing 1m candlesticks, how do you handle that?

**Comment by ikidnapmyself** [comment]
hello there! it's a nice point. in fact it would be sad to have a missing candle in an actual system. according to your question i have found this tiny article to get historical data of Binance. unfortunately im not using this script in a current project so i am not about to update it soon. pr is more than welcome!

https://medium.com/@samuelson78x/binance-get-historical-data-api-1bc8c758fa85
